### PR TITLE
Another JAVA Solution For Day 6 Problem

### PR DESCRIPTION
**Pull request by agrawroh**
Another JAVA solution for Day 6 problem for Hacker Rank 30 Days of Code.

### CODE REVIEW

**Comment by agrawroh** [comment]
Without any inner loops.
Much better performance.

**Comment by upa8** [comment]
Really awesome !!!

**Comment by upa8** [comment]
Hey @agrawroh , 
Your code is short and readable but it is also using inner loop . Because Arrays.fill() function is nothing but a inner loop . So according to me , it is still a two loop answer . Correct me if I am wrong :)

**Comment by tamycova** [comment]
@upa8 if it was python I would assume that as its a java function its more optimized than writing your own inner loops, @agrawroh correct me if Im wrong

**Comment by agrawroh** [comment]
The available documentation for Arrays.fill() method suggests that it just does use an inner loop to fill the Array Range. My guess is that it is performance optimized and hence save a bit of time.

**Comment by upa8** [comment]
Yes , you are right @agrawroh that it save a bit of time . As it is library function so it is well optimized but in your comment you were saying that your solution is without inner loop . It does use inner loop .

**Comment by agrawroh** [comment]
My bad. I just meant that I have not coded any inner loops in the proposed solution. Internally Arrays.fill() might be doing it.

**Comment by upa8** [comment]
Yes bro . But your solution was quite readable and efficient :) Happy coding !!!

**Pull request merged**
