### PR TITLE
[Swift] Day 26 -- Solution 2

### PR DESCRIPTION
**Pull request by swinful**
This implementation to day 26 solution is probably overkill. Just saw the solutions in other languages and it could have been much simpler.

### CODE REVIEW

**Comment by della-90** [comment]
Hi, I get the following compilation error:

```
solution.swift:122:14: error: value of type 'Date' has no member 'differenceBetweenDates'
var days = returned.differenceBetweenDates(expected)
           ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~`
```

**Comment by swinful** [comment]
Will fix that as soon as I get hope from work. Must have missed it while copy pasting from Xcode.
Thanks for catching it. 

Sent from Outlook Mobile

On Wed, Jan 27, 2016 at 3:30 PM -0800, "Nicola" notifications@github.com wrote:

Hi, I get the following compilation error:

solution.swift:122:14: error: value of type 'Date' has no member 'differenceBetweenDates'
var days = returned.differenceBetweenDates(expected)
           ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~`

**Comment by della-90** [comment]
No problem :smile:
Then I'll merge it as soon as possible

**Comment by swinful** [comment]
just pushed the corrections.

**Pull request merged**
