### PR TITLE
Create Solution3.swift

### PR DESCRIPTION
**Pull request by Ashok-Varma**
Drastically decreased times but still Test case 6 timeout

### CODE REVIEW

**Comment by della-90** [comment]
@tamycova should we merge solutions that does not pass all test cases? This applies also for #152

**Comment by della-90** [comment]
@Ashok-Varma By the way I think that you can drastically improve the execution time by creating a global immutable `validationArray` instead of creating it inside the method (which can be called thousand of times), like this:

```
let validationArray: Array<Character> = [" ","!","[",",","?",".","\\","_","\'","@","+","]"]
func shouldSplit(char: Character ) -> Bool{
    ....
}
```

**Comment by Ashok-Varma** [comment]
@della-90 missed that :p. changed code, Now working for all test cases you can merge this

but in general swift works completely differently. After this it increased time for many but test case 6 is passing.

if we write var a = b and b is array it won't copy b to a immediately when you change something in b then it will copy to it that to it won't copy complete array it just remembers the changes.

Other programming patterns work differently here.

**Comment by della-90** [comment]
@Ashok-Varma Ok, thanks! Can you please also rename `Solution1.swift` to `Solution3.swift`? Thanks :smile:

**Comment by Ashok-Varma** [comment]
@della-90 why ??
Only solution1 and solution2 are there

**Comment by della-90** [comment]
See #152:  it has conflicts

**Comment by Ashok-Varma** [comment]
@della-90 I didn't saw you committed Solution1 when i created pull request there are no Solutions even in requests. Any way Done. :p

**Comment by della-90** [comment]
Yup thanks, I merged some other stuff before :)

**Pull request merged**
