### PR TITLE
[Ruby] Day 27

### PR DESCRIPTION
**Pull request by misho-kr**

### CODE REVIEW

**Comment by della-90** [comment]
Hi @misho-kr, please correct me if I am wrong (I'm not a Ruby developer, so I can miss something), but I don't think that inside your code there's a way to ensure `N` to be unique in all test cases (or at least in the first 5 tests), so there could be an "unlucky situation" where your submission doesn't get all 100 points.

**Comment by misho-kr** [comment]
Your Ruby code reading skills are perfect, and I am not a Ruby dev either :). 

I completely missed that part of the requirements. Thanks for the code review. I am submitting an update to my code.

**Comment by misho-kr** [comment]
It is difficult to write perfect code. I am suspicious that even the "improved" version is not 100% error-proof -- few more checks are needed to guarantee the generated tests meets the requirements. But I think I hit my time limit for this problem.

**Comment by della-90** [comment]
You are right, but your code is perfect from my point of view! Thank you again for the changes :smile:

**Comment by misho-kr** [comment]
Thank you for doing all this work Nicola.

I wouldn't not have finished the challenge without this project. I enjoyed reading all contributions in other languages by my fellow developers.

**Comment by della-90** [comment]
You're welcome, I enjoyed taking care of this repo! This "work" also allowed me to take a look at many different languages and, as you said, learn something new!

**Pull request merged**
