### PR TITLE
Swift Folder rearranged and organised with day folders similar to Java

### PR DESCRIPTION
**Pull request by Ashok-Varma**
All Solutions organised

### CODE REVIEW

**Comment by Ashok-Varma** [comment]
@tamycova can you accept this before others submit solutions for next question. Again many conflicts will raise

**Comment by Ashok-Varma** [comment]
@swinful @della-90 we will follow this format, so solutions will be better organised.

Even there are multiple solutions in only 2 cases. after 30 questions old format will look messed up. So, i guess organising(similar to java) day wise will be better. What you guys think ?

**Comment by della-90** [comment]
Yes, I think it's the best way to store solutions. I'll try to change other solutions as well

**Comment by swinful** [comment]
I am okay with it. There are no other pull requests other than this, so there should be very few conflicts.

**Comment by della-90** [comment]
I reorganized everything. There may be some mistakes, if someone spots them please open an issue or add changes to a pull request! Thanks

**Comment by swinful** [comment]
Looks good. I was able pull your latest changes into my forked version without any conflicts. Thanks!

**Comment by Ashok-Varma** [comment]
All organised well

**Pull request merged**
